# Лабораторная работа 9: оценка качества классификации

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from  sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score, precision_recall_curve

## 1. Загрузите файл classification.csv. В нем записаны истинные классы объектов выборки (колонка true) и ответы некоторого классификатора (колонка predicted).

In [2]:
data_clf = pd.read_csv('classification.csv')
data_clf

     true  pred
0       1     0
1       1     1
2       1     1
3       0     0
4       1     1
..    ...   ...
195     0     0
196     0     0
197     1     0
198     0     1
199     0     0

[200 rows x 2 columns]

## 2. Заполните таблицу ошибок классификации: подсчитайте величины TP, FP, FN и TN. Ответ — четыре числа через пробел.

In [45]:
TP = len(data_clf[(data_clf['true'] == 1) & (data_clf['pred'] == 1)])
TN = len(data_clf[(data_clf['true'] == 0) & (data_clf['pred'] == 0)])
FP = len(data_clf[(data_clf['true'] == 0) & (data_clf['pred'] == 1)])
FN = len(data_clf[(data_clf['true'] == 1) & (data_clf['pred'] == 0)])

ans_1 = TP, FP, FN, TN

with open('1.txt', 'w') as file:
    file.write(f'{TP} {FP} {FN} {TN}')

## 3. Посчитайте основные метрики качества классификатора: Accuracy, Precision, Recall, F-measure. Ответ — четыре числа через пробел (округлённые до двух знаков).

In [46]:
accuracy = accuracy_score(data_clf['true'], data_clf['pred'])
precision = precision_score(data_clf['true'], data_clf['pred'])
recall = recall_score(data_clf.true, data_clf.pred)
f1 = f1_score(data_clf.true, data_clf.pred)

ans_2 = accuracy, precision, recall, f1
with open('2.txt', 'w') as file:
    file.write(f'{accuracy:.2f} {precision:.2f} {recall:.2f} {f1:.2f}')

## 4. Загрузите файл scores.csv. В нем записаны истинные классы и значения степени принадлежности положительному классу для четырёх классификаторов: score_logreg, score_svm, score_knn, score_tree.

In [42]:
data_score = pd.read_csv('scores.csv')
data_score

     true  score_logreg  score_svm  score_knn  score_tree
0       0      0.683832   0.145976   0.787063    0.500000
1       1      0.801966   0.239511   1.000000    0.833333
2       0      0.382315  -0.245701   0.000000    0.000000
3       1      0.506797  -0.137058   0.000000    0.105263
4       1      0.488781  -0.154148   0.000000    0.105263
..    ...           ...        ...        ...         ...
195     0      0.573801  -0.088203   0.284192    0.400000
196     0      0.624422  -0.012315   0.205437    0.400000
197     1      0.425538  -0.135673   0.382351    0.700000
198     0      0.905270   0.583806   1.000000    1.000000
199     0      0.275594  -0.422160   0.743567    0.642857

[200 rows x 5 columns]

## 5. Посчитайте площадь под ROC-кривой для каждого классификатора. Какой классификатор имеет наибольшее значение метрики AUC-ROC? Укажите название столбца с ответами этого классификатора.

In [51]:
clm_name = list(data_score.columns)[1:]

dict_roc_auc = {name: roc_auc_score(data_score.true, data_score.loc[:, name]) for name in clm_name}
ans_3 = max(dict_roc_auc, key=dict_roc_auc.get)

with open('3.txt', 'w') as file:
    file.write(f'{ans_3}')

## 6. Какой классификатор достигает наибольшей точности (Precision) при полноте (Recall) не менее 70%? Укажите название столбца с ответами этого классификатора.

In [58]:
a = precision_recall_curve(data_score.true, data_score.score_knn)[:-1]

In [67]:
dict_pr = {}
for name in clm_name:
    prc = precision_recall_curve(data_score.true, data_score.loc[:, name])
    pres_ = prc[0][prc[1]>=0.7].max()
    dict_pr[name] = pres_
ans_4 = max(dict_pr, key=dict_pr.get)

with open('4.txt', 'w') as file:
    file.write(f'{ans_4}')