### 1. Загрузите данные из файла abalone.csv.
Это датасет,в котором требуется предсказать возраст ракушки (число колец) по физическим
измерениям.

In [1]:
import pandas as pd

df = pd.read_csv('abalone.csv')
df

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

### 2. Преобразуйте признак Sex в числовой: 
значение F должно перейти в -1, I — в 0, M — в 1. 
Если вы используете Pandas, то подойдет
следующий код: 
```
data[’Sex’] = data[’Sex’].map(lambda x: 1 if x == ’M’ else (-1 if x == ’F’ else 0))
```

In [2]:
df['Sex'] = df['Sex'].map(lambda x: 1 if x == 'M' else (-1 if x == 'F' else 0))

### 3. Разделите содержимое файлов на признаки и целевую переменную.
В последнем столбце записана целевая переменная, в остальных —
признаки.

In [3]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight
0,1,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,-1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,1,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,0,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...,...
4172,-1,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,1,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,1,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,-1,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,1,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

### 4. Обучите случайный лес (sklearn.ensemble.RandomForestRegressor)
с различным числом деревьев: от 1 до 50 `(random_state=1)`. Для
каждого из вариантов оцените качество работы полученного леса
на кросс-валидации по 5 блокам. Используйте параметры
`"random_state=1"и "shuﬄe=True"` при создании генератора кросс-
валидации `sklearn.cross_validation.KFold`.
В качестве меры качества воспользуйтесь коэффициентом детерминации `(sklearn.metrics.r2_score)`.

In [4]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.metrics import r2_score

rfr = RandomForestRegressor(random_state = 1)
kfold = KFold(n_splits = 5, random_state = 1, shuffle = True)
params_grid = {
    'n_estimators': list(range(1,51))
}
grid_search = GridSearchCV(estimator = rfr, param_grid = params_grid, scoring = 'r2', cv = kfold, n_jobs = -1)
grid_search.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
             estimator=RandomForestRegressor(random_state=1), n_jobs=-1,
             param_grid={'n_estimators': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                          13, 14, 15, 16, 17, 18, 19, 20, 21,
                                          22, 23, 24, 25, 26, 27, 28, 29, 30, ...]},
             scoring='r2')

In [5]:
grid_search.cv_results_['mean_test_score'].shape

(50,)

### 5. Определите, при каком минимальном количестве деревьев случайный лес показывает качество на кросс-валидации выше 0.52. 
Это количество и будет ответом на задание.

In [6]:
import numpy as np
np.where(grid_search.cv_results_['mean_test_score']> 0.52)[0].min()+1

21

### 6. Обратите внимание на изменение качества по мере роста числа деревьев. Ухудшается ли оно?

In [7]:
r2_scores = grid_search.cv_results_['mean_test_score']
ans = pd.DataFrame({
    'r2_scores': r2_scores,
    'diff with previous': np.insert(np.diff(r2_scores), 0, 0),
    'increases?': ((np.sign(np.insert(np.diff(r2_scores), 0, 0))+1)/2).astype('bool')
})
print(ans)
print('Не ухудшается')

    r2_scores  diff with previous  increases?
0    0.109675            0.000000        True
1    0.341300            0.231625        True
2    0.406434            0.065134        True
3    0.444775            0.038341        True
4    0.465032            0.020258        True
5    0.471396            0.006364        True
6    0.476666            0.005270        True
7    0.482935            0.006269        True
8    0.489437            0.006502        True
9    0.495409            0.005972        True
10   0.494411           -0.000997       False
11   0.499028            0.004617        True
12   0.503058            0.004030        True
13   0.507317            0.004259        True
14   0.509181            0.001864        True
15   0.511411            0.002230        True
16   0.514892            0.003481        True
17   0.517220            0.002329        True
18   0.519829            0.002609        True
19   0.519484           -0.000345       False
20   0.520529            0.001045        True
21   0.520804            0.000275        True
22   0.521743            0.000938        True
23   0.523106            0.001363        True
24   0.523249            0.000143        True
25   0.524308            0.001059        True
26   0.524639            0.000332        True
27   0.525656            0.001016        True
28   0.526556            0.000900        True
29   0.527086            0.000530        True
30   0.527642            0.000556        True
31   0.528924            0.001282        True
32   0.530107            0.001183        True
33   0.529961           -0.000146       False
34   0.529821           -0.000140       False
35   0.529910            0.000089        True
36   0.529432           -0.000478       False
37   0.529472            0.000039        True
38   0.529516            0.000044        True
39   0.529470           -0.000046       False
40   0.529809            0.000338        True
41   0.530043            0.000235        True
42   0.529914           -0.000130       False
43   0.529681           -0.000232       False
44   0.528908           -0.000773       False
45   0.529008            0.000100        True
46   0.529179            0.000170        True
47   0.530051            0.000872        True
48   0.530813            0.000762        True
49   0.530951            0.000138        True
Не ухудшается