# Лабораторная работа 2: решающее дерево на данных Titanic

## 1. Загрузите выборку из файла `titanic.csv` с помощью пакета Pandas.

In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder

In [5]:
data = pd.read_csv('titanic.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 2. Оставьте в выборке четыре признака: класс пассажира (Pclass), цену билета (Fare), возраст пассажира (Age) и его пол (Sex).

## 3. Обратите внимание, что признак Sex имеет строковые значения.

## 4. Выделите целевую переменную — она записана в столбце Survived.

## 5. В данных есть пропущенные значения — например, для некоторых пассажиров неизвестен их возраст. Такие записи при чтении их в pandas принимают значение nan. Найдите все объекты, у которых есть пропущенные признаки, и удалите их из выборки.

In [6]:
data_withoutnan = data.dropna()
X = data_withoutnan[['Pclass', 'Sex', 'Age', 'Fare']]
y_target = data_withoutnan.Survived

Преобразование строкового признака `Sex` в числовой с помощью OneHotEncoding (drop_first).

In [7]:
X_train = X.copy()
X_train[['Sex']] = OneHotEncoder(drop='first', sparse_output=False, dtype=int).fit_transform(X[['Sex']])
X_train

     Pclass  Sex   Age     Fare
1         1    0  38.0  71.2833
3         1    0  35.0  53.1000
6         1    1  54.0  51.8625
10        3    0   4.0  16.7000
11        1    0  58.0  26.5500
..      ...  ...   ...      ...
871       1    0  47.0  52.5542
872       1    1  33.0   5.0000
879       1    0  56.0  83.1583
887       1    0  19.0  30.0000
889       1    1  26.0  30.0000

[183 rows x 4 columns]

## 6. Обучите решающее дерево с параметром random_state=241 и остальными параметрами по умолчанию.

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
dt_model = DecisionTreeClassifier(random_state=241)
dt_fit = dt_model.fit(X_train, y_target)

## 7. Вычислите важности признаков и найдите два признака с наибольшей важностью. Их названия будут ответами для данной задачи (в качестве ответа укажите названия признаков через запятую без пробелов).

In [10]:
feat_import = pd.DataFrame({'feature': X_train.columns, 'feature_importances': dt_fit.feature_importances_})
feat_import = feat_import.sort_values('feature_importances', ascending=False, ignore_index=True) 
ans = feat_import.loc[:1, 'feature']

with open('1.txt', 'w') as file:
    file.write(f'{ans[0]},{ans[1]}')