In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML_intro/01/titanic.csv', index_col='PassengerId')

In [3]:
data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
data['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

1. Какое количество мужчин и женщин ехало на корабле? В качестве
ответа приведите два числа через пробел.

In [5]:
sex_count = data['Sex'].value_counts()
print(sex_count['male'], ' ', sex_count['female'])

577   314

2. Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух
знаков.

In [6]:
survived_count = data['Survived'].value_counts()
part = survived_count [1] / data['Survived'].count()
part *= 100
part = part.round(2)
print(part)

38.38

3. Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до
100, знак процента не нужен), округлив до двух знаков.

In [7]:
class_count = data['Pclass'].value_counts()
part = class_count[1] / data['Pclass'].count()
part *= 100
part = part.round(2)
print(part)

24.24

4. Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. Посчитайте среднее и медиану возраста
пассажиров. В качестве ответа приведите два числа через пробел.

In [8]:
mean_age = data['Age'].mean()
median_age = data['Age'].median()
print(mean_age.round(1), ' ', median_age)

29.7   28.0

5. Коррелируют ли число братьев/сестер с числом родителей/детей?
Посчитайте корреляцию Пирсона между признаками SibSp и Parch.

In [9]:
def Pirson(all_sum, x_sum, y_sum):
  r = all_sum / np.sqrt(x_sum * y_sum)
  return r

In [10]:
all_sum = 0
x_sum = 0
y_sum  = 0

sibsp = data['SibSp']
parch = data['Parch']

x_mean = sibsp.mean()
y_mean = parch.mean()

for i in range(len(data)):
  x = sibsp.iloc[i]
  y = parch.iloc[i]
  x_x = x - x_mean
  y_y = y - y_mean

  all_sum += x_x * y_y
  x_sum += x_x**2
  y_sum += y_y**2

correlation = Pirson(all_sum, x_sum, y_sum)
print(correlation.round(2))

0.41

6. Какое самое популярное женское имя на корабле? Извлеките из
полного имени пассажира (колонка Name) его личное имя (First
Name). Это задание — типичный пример того, с чем сталкивается специалист по анализу данных. Данные очень разнородные и
шумные, но из них требуется извлечь необходимую информацию.
Попробуйте вручную разобрать несколько значений столбца Name
и выработать правило для извлечения имен, а также разделения
их на женские и мужские.

In [11]:
first_names = []
for i in range(len(data)):
  name = data['Name'].iloc[i]
  if 'Mr.' in name or 'Miss.' in name or ("Mrs." in name and '(' not in name):
    first_name = name.split('.')[1].split(' ')[1]
  elif "Mrs." in name and '(' in name:
    first_name = name.split('(')[1].split(' ')[0]
  first_name = re.sub(r'[^a-zA-Zа]', '', first_name)
  first_names.append(first_name)
data['First Name'] = first_names

In [12]:
print((data.loc[data['Sex'] == 'female', 'First Name'].mode()).iloc[0])

Anna