### 1. Загрузите выборку из файла titanic.csv с помощью пакета Pandas.

In [10]:
import pandas as pd
titanic = pd.read_csv('titanic.csv', index_col = 'PassengerId')

In [11]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [12]:
titanic.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [13]:
titanic.sample(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.0,0,2,2653,15.7417,NaN,C
59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,NaN,S
570,1,3,"Jonsson, Mr. Carl",male,32.0,0,0,350417,7.8542,NaN,S
737,0,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,NaN,S
277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45.0,0,0,347073,7.7500,NaN,S
792,0,2,"Gaskell, Mr. Alfred",male,16.0,0,0,239865,26.0000,NaN,S
245,0,3,"Attalah, Mr. Sleiman",male,30.0,0,0,2694,7.2250,NaN,C
346,1,2,"Brown, Miss. Amelia ""Mildred""",female,24.0,0,0,248733,13.0000,F33,S
665,1,3,"Lindqvist, Mr. Eino William",male,20.0,1,0,STON/O 2. 3101285,7.9250,NaN,S
858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S

### Оставьте в выборке четыре признака: 
класс пассажира (Pclass), це ну билета (Fare), возраст пассажира (Age) и его пол (Sex).

In [14]:
titanic_4 = titanic[['Pclass', 'Fare', 'Age', 'Sex']].copy()

### 3. Обратите внимание, что признак Sex имеет строковые значения.

In [15]:
titanic_4['Sex'] = titanic_4['Sex'].map({'male': 1, 'female':0})

### 4. Выделите целевую переменную — она записана в столбце Survived.

In [16]:
target = titanic['Survived']

### 5. В данных есть пропущенные значения — например, для некоторых пассажиров неизвестен их возраст. 
Такие записи при чтении их в
pandas принимают значение nan. Найдите все объекты, у которых
есть пропущенные признаки, и удалите их из выборки.

In [17]:
X = titanic_4.dropna()
Y = target[X.index]

### 6. Обучите решающее дерево с параметром random_state=241
и остальными параметрами по умолчанию.

In [41]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(random_state = 241)
tree.fit(X,Y)

DecisionTreeClassifier(random_state=241)

### 7. Вычислите важности признаков и найдите два признака с наибольшей важностью. 
Их названия будут ответами для данной задачи
(в качестве ответа укажите названия признаков через запятую без
пробелов).

In [47]:
importance = pd.Series(tree.feature_importances_, index = tree.feature_names_in_).sort_values(ascending = False)
print(','.join(importance.iloc[:2].index.to_list()))

Fare,Sex