# Лабораторная работа №1

In [8]:
import pandas as pd

titanic = pd.read_csv('titanic.csv', index_col = 'PassengerId')

In [19]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [17]:
titanic.sample(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
800,0,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S
675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0000,NaN,S
580,1,3,"Jussila, Mr. Eiriik",male,32.0,0,0,STON/O 2. 3101286,7.9250,NaN,S
190,0,3,"Turcin, Mr. Stjepan",male,36.0,0,0,349247,7.8958,NaN,S
406,0,2,"Gale, Mr. Shadrach",male,34.0,1,0,28664,21.0000,NaN,S
833,0,3,"Saad, Mr. Amin",male,NaN,0,0,2671,7.2292,NaN,C
19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
619,1,2,"Becker, Miss. Marion Louise",female,4.0,2,1,230136,39.0000,F4,S
36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
772,0,3,"Jensen, Mr. Niels Peder",male,48.0,0,0,350047,7.8542,NaN,S

In [18]:
titanic.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### 1. Какое количество мужчин и женщин ехало на корабле? 
В качестве
ответа приведите два числа через пробел.

In [96]:
print(*titanic['Sex'].value_counts().to_list())

577 314

### 2. Какой части пассажиров удалось выжить? 
Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в ин-
тервале от 0 до 100, знак процента не нужен), округлив до двух
знаков.

In [95]:
print((titanic['Survived'].mean()*100).round(2))

38.38

### 3. Какую долю пассажиры первого класса составляли среди всех пассажиров? 
Ответ приведите в процентах (число в интервале от 0 до
100, знак процента не нужен), округлив до двух знаков.

In [94]:
print((titanic['Pclass'].value_counts(normalize = True)[1]*100).round(2))

24.24

### 4. Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. 
Посчитайте среднее и медиану возраста
пассажиров. В качестве ответа приведите два числа через пробел.

In [100]:
print(*titanic.describe().loc[['mean', '50%'], 'Age'].round(2).to_list())

29.7 28.0

### 5. Коррелируют ли число братьев/сестер с числом родителей/детей?
Посчитайте корреляцию Пирсона между признаками SibSp и Parch

In [101]:
print(titanic['SibSp'].corr(titanic['Parch']).round(2))

0.41

### 6. Какое самое популярное женское имя на корабле? 
Извлеките из полного имени пассажира (колонка Name) его личное имя (First
Name).

In [82]:
import re

def get_first_name(full_name):
    
    s = str(full_name)

    m_title = re.search(r',\s*([^.]+)\.', s)
    title = m_title.group(1).strip() if m_title else None

    if title == 'Mrs':
        m_paren = re.search(r'\(([^)]+)\)', s)
        if m_paren:
            s = m_paren.group(1)
        else:
            s = re.sub(r'^.*?\.\s*', '', s)  # после титула
    else:
        s = re.sub(r'^.*?\.\s*', '', s)      # после титула

    m_name = re.search(r"[A-Za-z]+(?:-[A-Za-z]+)?", s)
    return m_name.group(0) if m_name else None

titanic['FirstName'] = titanic['Name'].apply(get_first_name)

top_female_name = titanic.loc[titanic['Sex'] == 'female', 'FirstName'].value_counts().idxmax()
print(top_female_name)

Anna